data:
    build: .
    hostname: data
    volumes:
        - ./data:/data
        - ./data/mysql:/var/lib/mysql
        - ./data/nexus:/sonatype-work
        - ./data/jenkins:/var/jenkins_home

mysql:
    image: mysql:latest
    hostname: mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=sonar
        - MYSQL_USER=sonar
        - MYSQL_PASSWORD=sonar
    restart: always
    volumes_from:
        - data

sonar:
    image: sonarqube:latest
    hostname: sonar
    links:
        - mysql
    ports:
        - 9000:9000
    environment:
        - SONARQUBE_JDBC_URL=jdbc:mysql://mysql/sonar?useUnicode=true&characterEncoding=utf8
        - SONARQUBE_JDBC_USERNAME=sonar
        - SONARQUBE_JDBC_PASSWORD=sonar
    restart: always

nexus:
    image: sonatype/nexus:oss
    hostname: nexus
    ports:
        - 8081:8081
    restart: always
    volumes_from:
        - data

jenkins:
    image: jenkinsci/jenkins:latest
    hostname: jenkins
    links:
        - mysql
        - sonar
        - nexus
    ports:
        - 8080:8080
    restart: always
    volumes_from:
        - data
